# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-04 16:45
from __future__ import unicode_literals

import blog.models
from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20190303_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('verified', models.BooleanField(default=False, verbose_name='Is verified')),
                ('profile_picture', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/shadab/Documents/Tech/deployed-projects/Excurcus/EX/media'), upload_to=blog.models.profile_image_upload_path)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
