# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-04 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190304_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verified',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
